### ISSUE TITLE
Have you ever obtained similar performance as in the paper?

### ISSUE THREAD

**Issue by JeyesHan** [Heonozis/FaceShifter-pytorch#1]
Thank you so much for your brilliant work. I am wondering the performance of your implementation currently. Have you gotten similar results?

**Comment by Heonozis** [comment]
Unfortunately no. I was just testing the concept. First of all, I downscaled the network to use 64x64 images. And also, I did only 50 epochs (in the paper they did 200K). But conceptually it works and I'll use this technique for face swap.

**Comment by Heonozis** [comment]
Close to inactivity
